services:
  - type: web
    name: colloki-backend
    env: python
    runtime: python
    region: oregon
    plan: free
    repo: https://github.com/your-username/your-repo-name  # Replace with your actual repo
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
